from enum import Enum


class SchemaKeyword(str, Enum):
    TYPE = "type"
    PROPERTIES = "properties"
    ADDITIONAL_PROPERTIES = "additionalProperties"
    ITEMS = "items"
    PATTERN = "pattern"
    MIN_LENGTH = "minLength"
    MAX_LENGTH = "maxLength"
    MINIMUM = "minimum"
    MAXIMUM = "maximum"
    EXCLUSIVE_MINIMUM = "exclusiveMinimum"
    EXCLUSIVE_MAXIMUM = "exclusiveMaximum"
    MIN_ITEMS = "minItems"
    MAX_ITEMS = "maxItems"
    UNIQUE_ITEMS = "uniqueItems"
    MIN_PROPERTIES = "minProperties"
    MAX_PROPERTIES = "maxProperties"
    MULTIPLE_OF = "multipleOf"
    ANY_OF = "anyOf"
    ONE_OF = "oneOf"
    ALL_OF = "allOf"
    NOT = "not"
    REQUIRED = "required"
    ENUM = "enum"
    CONST = "const"
    FORMAT = "format"
    DESCRIPTION = "description"
    TITLE = "title"
    DEFAULT = "default"
